### PR TITLE
Configure the Memcached implementation

### PR DESCRIPTION
**Pull request by rinatkhaziev**
We already had the Memcached service running. However, it was missing the necessary config - specifying the port and defining the memcached_servers global per  wp-memcached [README](https://github.com/Automattic/wp-memcached).

The final piece would be to add the object-cache-stable.php from stacks and allow for conditionally enabling/disabling it.

### CODE REVIEW

**Review by brandon-m-skinner — APPROVED** [review]

**Comment by rinatkhaziev** [comment]
Currently, something is not quite right with Lando and Memcached - I haven't figured that part out yet, but it's slower than it should be (by A LOT), utterly destroying both Lando's and host's performance.

**Comment by WPprodigy** [comment]
@rinatkhaziev Seems it's still missing the dropin piece: https://github.com/Automattic/wp-memcached

**Comment by rinatkhaziev** [comment]
@WPprodigy I was not able to make it work reliably locally as per previous comment, so I slapped the 'Do not merge' label and successfully forgot about it. Were you able to make it work?

**Comment by WPprodigy** [comment]
Yep, adding the dropin is all that was needed for me. Did it manually versus in a build-friendly way though.

**Comment by rinatkhaziev** [comment]
@WPprodigy and you didn't experience any performance hit with the above settings?

**Comment by WPprodigy** [comment]
All seems normal and fast in both web requests and shell. Can test with:

```
define( 'CANARY_KEY', 'canary' );
define( 'CANARY_VALUE', 'canary' );

add_action( 'init', function() {
	if ( isset( $_GET['setup_memcache_test'] ) ) {
		wp_cache_set( CANARY_KEY, CANARY_VALUE );
	}

	$canary = wp_cache_get( CANARY_KEY );
	if ( $canary !== CANARY_VALUE ) {
		echo "UH OH!";
	} else {
		echo "SUCCESS";
	}
	die();
});
```

After a `?setup_memcache_test` request, subsequent requests should be SUCCESS still. Without the dropin though, it has no way of persisting between requests.

I'll see if I can find a good way to get the dropin to be placed at `wp/wp-content/object-cache.php` during the build 🤔

**Comment by WPprodigy** [comment]
Latest commit adds the final piece:

1) Pulls down the repo in the project root: https://github.com/Automattic/wp-memcached
2) Mounts `object-cache.php` in the `wp-content` folder.

**Comment by WPprodigy** [comment]
Well, there is this: https://github.com/Automattic/vip-go-mu-plugins/tree/master/drop-ins. Perhaps better than pulling the wp-memcached git repo down since it's unlikely to be actively developed.

Will need to mount the contents of the `drop-ins` folder from inside an already mounted location in docker though 🤔

**Comment by rinatkhaziev** [comment]
@WPprodigy we've bumped the drop-ins wp-memcached to the latest and greatest, is it possible to modify the PR to put a symlink (if nothing exists at wp-content/object-cache.php) instead of cloning here?

**Comment by rinatkhaziev** [comment]
I'm closing this since this iteration of dev-env is about to be replaced with the new cool thing.

**Comment by WPprodigy** [comment]
👍 . Need to make sure memcache is hooked up there xD

**Pull request closed without merging**
